pipeline {
    agent any
    environment {
  dotnet = 'path\\to\\dotnet.exe'
 }
    stages {
        stage('stage 1')
		{
			steps{
				echo 'Retrieving source from github' 
                git branch: 'main',
                    url: 'https://github.com/irfan1pathan/demo-windows-docker.git'
                echo 'Did we get the source?' 
                sh 'ls -a'
			}
		}
        stage('Restore PACKAGES') {
   steps {
    bat "dotnet restore --configfile NuGet.Config"
   }
  }
  stage('Clean') {
   steps {
    bat 'dotnet clean'
   }
  }
  stage('Build') {
   steps {
    bat 'dotnet build --configuration Release'
   }
  }
    }
}