pipeline{
    agent any
	
	stages{
		stage('stage 1')
		{
			steps{
				echo 'Retrieving source from github' 
                git branch: 'main',
                    url: 'https://github.com/irfan1pathan/demo-windows-docker.git'
                echo 'Did we get the source?' 
                sh 'ls -a'
			}
		}
	}
}